name: Build & deploy redis
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Read version from file
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build ./redis/ --file Dockerfile --tag looking_glass_redis:${{ env.VERSION }}
    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/looking_glass_redis:${{ env.VERSION }}
